version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: always
    build: ./postgress-db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - custom-service
    env_file:
      - .env
    command:
      [
        'postgres',
        '-c',
        'logging_collector=on',
        '-c',
        'log_statement=all',
        '-c',
        'log_directory=/logs',
      ]
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/logs
  app:
    container_name: app
    restart: always
    build: ./
    volumes:
      - .:/app/src
      - node-modules:/usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    networks:
      - custom-service

networks:
  custom-service:
    driver: bridge

volumes:
  logs:
  pgdata:
  app:
  node-modules:
