version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: always
    build: ./postgress-db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - custom-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
  node:
    container_name: node
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    networks:
      - custom-service

networks:
  custom-service:
    driver: bridge

volumes:
  pgdata:
